# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WavesCheck' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WavesCheck

pod 'FirebaseAuth'
pod 'Firebase/Core'
pod 'FirebaseFirestore'
pod 'Firebase/Database'
pod 'Firebase/Storage'

end
